/**
  LIN Slave Application
	
  Company:
    Microchip Technology Inc.

  File Name:
    lin_app.h

  Summary:
    LIN Slave Application

  Description:
    This header file provides the interface between the user and 
    the LIN drivers.

 */

/*
    (c) 2016 Microchip Technology Inc. and its subsidiaries. You may use this
    software and any derivatives exclusively with Microchip products.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
    WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

    MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
    TERMS.
*/


#ifndef LIN_APP_H
#define	LIN_APP_H

#include "lin_slave.h"

typedef enum {
    OUTPUT_MODULE_0,
    OUTPUT_MODULE_1,
    OUTPUT_MODULE_2,
    OUTPUT_MODULE_3,
    OUTPUT_MODULE_4,
    OUTPUT_MODULE_5,
    OUTPUT_MODULE_6,
    OUTPUT_MODULE_7,
    OUTPUT_MODULE_8,
    OUTPUT_MODULE_9,
    OUTPUT_MODULE_10,
    OUTPUT_MODULE_11,
    OUTPUT_MODULE_12,
    OUTPUT_MODULE_13,
    OUTPUT_MODULE_14,
    OUTPUT_MODULE_15
}lin_cmd_t;

uint8_t OUTPUT_MODULE_0_Data[1];
uint8_t OUTPUT_MODULE_1_Data[1];
uint8_t OUTPUT_MODULE_2_Data[1];
uint8_t OUTPUT_MODULE_3_Data[1];
uint8_t OUTPUT_MODULE_4_Data[1];
uint8_t OUTPUT_MODULE_5_Data[1];
uint8_t OUTPUT_MODULE_6_Data[1];
uint8_t OUTPUT_MODULE_7_Data[1];
uint8_t OUTPUT_MODULE_8_Data[1];
uint8_t OUTPUT_MODULE_9_Data[1];
uint8_t OUTPUT_MODULE_10_Data[1];
uint8_t OUTPUT_MODULE_11_Data[1];
uint8_t OUTPUT_MODULE_12_Data[1];
uint8_t OUTPUT_MODULE_13_Data[1];
uint8_t OUTPUT_MODULE_14_Data[1];
uint8_t OUTPUT_MODULE_15_Data[1];

const lin_rx_cmd_t scheduleTable[] = {
    //Command, Type, TX/RX Length, Data Address
    {OUTPUT_MODULE_0, RECEIVE, 1, OUTPUT_MODULE_0_Data },
    {OUTPUT_MODULE_1, RECEIVE, 1, OUTPUT_MODULE_1_Data },
    {OUTPUT_MODULE_2, RECEIVE, 1, OUTPUT_MODULE_2_Data },
    {OUTPUT_MODULE_3, RECEIVE, 1, OUTPUT_MODULE_3_Data },
    {OUTPUT_MODULE_4, RECEIVE, 1, OUTPUT_MODULE_4_Data },
    {OUTPUT_MODULE_5, RECEIVE, 1, OUTPUT_MODULE_5_Data },
    {OUTPUT_MODULE_6, RECEIVE, 1, OUTPUT_MODULE_6_Data },
    {OUTPUT_MODULE_7, RECEIVE, 1, OUTPUT_MODULE_7_Data },
    {OUTPUT_MODULE_8, RECEIVE, 1, OUTPUT_MODULE_8_Data },
    {OUTPUT_MODULE_9, RECEIVE, 1, OUTPUT_MODULE_9_Data },
    {OUTPUT_MODULE_10, RECEIVE, 1, OUTPUT_MODULE_10_Data },
    {OUTPUT_MODULE_11, RECEIVE, 1, OUTPUT_MODULE_11_Data },
    {OUTPUT_MODULE_12, RECEIVE, 1, OUTPUT_MODULE_12_Data },
    {OUTPUT_MODULE_13, RECEIVE, 1, OUTPUT_MODULE_13_Data },
    {OUTPUT_MODULE_14, RECEIVE, 1, OUTPUT_MODULE_14_Data },
    {OUTPUT_MODULE_15, RECEIVE, 1, OUTPUT_MODULE_15_Data }
};
#define TABLE_SIZE  (sizeof(scheduleTable)/sizeof(lin_rx_cmd_t))

void LIN_Slave_Initialize(void);

void processLIN(void);


#endif	/* LIN_APP_H */

